# Generated by Django 2.2.4 on 2021-03-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title: ')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug :')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title: ')),
            ],
            options={
                'verbose_name': 'Blog_Categoty',
                'verbose_name_plural': 'Blog_Categories',
            },
        ),
    ]
